"""
This type stub file was generated by pyright.
"""

import polars as pl

"""
This type stub file was generated by pyright.
"""

def apply_expr_to_series(series: pl.Series, expr: pl.Expr) -> pl.Series: ...
